if: tag IS blank

git:
  depth: 10

language: node_js
node_js:
  - '12'
  - '14'

cache:
  directories:
    - node_modules

before_install:
  - openssl version
  - npm root -g
  - echo $TRAVIS_COMMIT_MESSAGE
  - npm i -g lerna
  - npm run bootstrap
  - echo "$TRAVIS_COMMIT_MESSAGE" | node_modules/.bin/commitlint 

#services:
#  - postgresql
#addons:
#  postgresql: "9.6"
#before_script:
#  - psql -U postgres -c "create database db_ci_test;"

install: true

script:
  - npm run build
  - npm run test

after_success:
  #- npm run cov:coveralls

